# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  schedule:
    - cron: '0 12 * * *'
    - cron: '30 9 * * *'
    - cron: '0 10 * * *'
  workflow_dispatch:
    inputs:
      deploymentEnvironment:
        description: 'The environment to deploy to'
        required: true
        type: choice
        options:
          - Dev1
          - Production 

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    outputs:
      account: ${{ steps.identify.outputs.account }}

    steps:
    - uses: actions/checkout@v4
    - name: SetEnv For Manual Cleanup
      id: identify
      run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            export Account="${{ github.event.inputs.deploymentEnvironment }}"
            echo "account=${Account}" >> $GITHUB_OUTPUT
          elif [[ "${{  github.event_name  }}" == "schedule" ]]; then
            echo "account=abc" >> $GITHUB_OUTPUT
          else
            echo "::set-env name=GHA_ENV::unknown"
          fi
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"


  test:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
    - uses: actions/checkout@v4
    - name: Test with pytest
      run: |
        pytest "${{ needs.build.outputs.account }}"
